/******************************CREATE DATABASE********************************/

CREATE DATABASE QUANLYDAOTAO_B4_MSSV
GO 
USE QUANLYDAOTAO_B4_MSSV

/************************TAO BANG KHOA QUAN LY SINH VIEN*************************/
CREATE TABLE KHOA(MAKHOA VARCHAR(4) NOT NULL ,
			TENKHOA NVARCHAR(30) NOT NULL,
			      NAMTHANHLAP INT NOT NULL)

/************************TAO BANG SVIEN QUAN LY SINH VIEN*************************/
CREATE TABLE SVIEN(TEN NVARCHAR(30) NOT NULL,
			MASV INT NOT NULL,
			   NAM INT NOT NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG MHOC QUAN LY SINH VIEN*************************/
CREATE TABLE MHOC(TENMH NVARCHAR(30) NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   TINCHI INT NOT NULL,
			      MAKH VARCHAR(4) NOT NULL)

/************************TAO BANG DKIEN QUAN LY SINH VIEN*************************/
CREATE TABLE DKIEN(MAMH VARCHAR(8) NOT NULL,
			MAMH_TRUOC VARCHAR(8) NOT NULL
			)


/************************TAO BANG HPHAN QUAN LY SINH VIEN*************************/
CREATE TABLE HPHAN(MAHP INT NOT NULL,
			MAMH VARCHAR(8) NOT NULL,
			   HOCKY INT NOT NULL,
			      NAM INT NOT NULL,
					GV NVARCHAR(30) NULL
			)

/************************TAO BANG KQUA QUAN LY SINH VIEN*************************/
CREATE TABLE KQUA(MASV INT NOT NULL,
			   MAHP INT NOT NULL,
			      DIEM FLOAT NOT NULL
			)

/*************************KHOA CHINH **********************************/
ALTER TABLE SVIEN
		ADD CONSTRAINT PK_SVIEN 
			PRIMARY KEY (MASV)
ALTER TABLE KHOA
		ADD CONSTRAINT PK_KHOA 
			PRIMARY KEY (MAKHOA)
ALTER TABLE MHOC
		ADD CONSTRAINT PK_MHOC 
			PRIMARY KEY (MAMH)
ALTER TABLE HPHAN
		ADD CONSTRAINT PK_HPHAN 
			PRIMARY KEY (MAHP)
ALTER TABLE KQUA
		ADD CONSTRAINT PK_KQUA 
			PRIMARY KEY (MASV,MAHP)
ALTER TABLE DKIEN
		ADD CONSTRAINT PK_DKIEN 
			PRIMARY KEY (MAMH,MAMH_TRUOC)
/***************************KHOA NGOAI***************************/
ALTER TABLE SVIEN 
		ADD CONSTRAINT FK_SVIEN_MAKH FOREIGN KEY (MAKH)
			REFERENCES KHOA (MAKHOA)
ALTER TABLE MHOC 
		ADD CONSTRAINT FK_MHOC_MAKH FOREIGN KEY (MAKH)
			REFERENCES KHOA (MAKHOA)
ALTER TABLE HPHAN 
		ADD CONSTRAINT FK_HPHAN_MAMH FOREIGN KEY (MAMH)
			REFERENCES MHOC (MAMH)
ALTER TABLE DKIEN 
		ADD CONSTRAINT FK_DKIEN_MAMH FOREIGN KEY (MAMH)
			REFERENCES MHOC (MAMH)
ALTER TABLE DKIEN 
		ADD CONSTRAINT FK_DKIEN_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC)
			REFERENCES MHOC (MAMH)
ALTER TABLE KQUA 
		ADD CONSTRAINT FK_KQUA_MASV FOREIGN KEY (MASV)
			REFERENCES SVIEN (MASV)
ALTER TABLE KQUA 
		ADD CONSTRAINT FK_KQUA_MAHP FOREIGN KEY (MAHP)
			REFERENCES HPHAN (MAHP)
			         

