/**********************************USE DATABASE********************************/

GO
USE QUANLYDAOTAO_B4_MSSV

INSERT INTO KHOA VALUES('CNTT',N'Công Nghệ Thông Tin',1995)
	INSERT INTO KHOA VALUES('VL',N'Vật Lý',1976)
		INSERT INTO KHOA VALUES('TOAN',N'Toán',1976)

INSERT INTO SVIEN VALUES(N'Sơn',17,1,'CNTT')
	INSERT INTO SVIEN VALUES(N'Bảo',8,2,'CNTT')
		INSERT INTO SVIEN VALUES(N'Trang',5,3,'TOAN')
		
INSERT INTO MHOC VALUES(N'Nhập Môn Tin Học','COSC1310',4,'CNTT')
	INSERT INTO MHOC VALUES(N'Cấu Trúc Dữ Liệu','COSC3320',4,'CNTT')	
		INSERT INTO MHOC VALUES(N'Toán Rời Rạc','MATH2410',3,'TOAN')
			INSERT INTO MHOC VALUES(N'Cơ Sở Dữ Liệu','COSC3380',3,'CNTT')
				INSERT INTO MHOC VALUES(N'Vật Lý Đại Cương','PHYS3332',3,'VL')

INSERT INTO DKIEN VALUES('COSC3380','COSC3320')
	INSERT INTO DKIEN VALUES('COSC3380','MATH2410')
		INSERT INTO DKIEN VALUES('COSC3320','COSC1310')

INSERT INTO HPHAN VALUES(85,'MATH2410',1,1996,N'Kim')
	INSERT INTO HPHAN VALUES(92,'COSC1310',1,1996,N'An')
		INSERT INTO HPHAN VALUES(102,'COSC3320',2,1997,N'Nhiên')
			INSERT INTO HPHAN VALUES(112,'MATH2410',1,1997,NULL)
				INSERT INTO HPHAN VALUES(119,'COSC1310',1,1997,N'An')
					INSERT INTO HPHAN VALUES(135,'COSC3380',1,1997,N'Sơn')

INSERT INTO KQUA VALUES(17,102,8)
	INSERT INTO KQUA VALUES(17,119,6)
		INSERT INTO KQUA VALUES(5,85,10)
			INSERT INTO KQUA VALUES(8,92,10)
				INSERT INTO KQUA VALUES(8,102,8)
					INSERT INTO KQUA VALUES(8,135,10)
/****************************HAM XUAT*********************************/
SELECT * FROM SVIEN 
SELECT * FROM DKIEN
SELECT * FROM KHOA 
SELECT * FROM MHOC 
SELECT * FROM HPHAN 
SELECT * FROM KQUA 

/****************************TRUY VAN DU LIEU************************/